---
title: "RQ1 - Spatial"
author: "Savannah K. Miller"
date: "2026-06-22"
output: html_document
---

<!--
Split from master_thesis_regressions.Rmd this session into RQ1-spatial.Rmd
(this file) and RQ1-temporal.qmd, so site/edge-type/distance/elevation
structure and Study.Phase/date trends can be read and run separately.
Moved OUT to RQ1-temporal.qmd: the "rq1 time" chunk (rq1_time_trend,
rq1_time -- both by Date.removed.from.field), and two of the three plots
from the "transect x site model with replicate and phase" chunk (the
Study.Phase sina plot and the Dist x Study.Phase facet plot) -- both show
patterns across Study.Phase, not across site/space. The transite1 model
itself and its Tran-by-Site boxplot stay here, since the model's actual
question is the Tran x Site interaction.
-->

```{r, load packages and working directory}

source("C:\\Users\\savan\\OneDrive - San Francisco State University\\ProjectData\\GitHub\\DepositionSFB\\code\\R\\setup.R")
source("C:\\Users\\savan\\OneDrive - San Francisco State University\\ProjectData\\GitHub\\DepositionSFB\\code\\R\\plotting.R")
source("C:\\Users\\savan\\OneDrive - San Francisco State University\\ProjectData\\GitHub\\DepositionSFB\\code\\R\\flux_summary.R")
```

```{r, working directory and master data file}

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = 'C:/Users/savan/OneDrive - San Francisco State University/ProjectData/GitHub/DepositionSFB/data')

master_tier5 <- readr::read_csv("C:\\Users\\savan\\OneDrive - San Francisco State University\\ProjectData\\GitHub\\DepositionSFB\\data\\master_tier5.csv")

master_tier5_clean <- master_tier5 |> 
  filter(Flux > 0, 
         Dist != 48)

month_levels <- c("Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
                   "Jan", "Feb", "Mar", "Apr", "May", "Jun")

master_tier5 <- master_tier5 %>%
  mutate(Month = factor(Month, levels = month_levels))

master_tier5_clean <- master_tier5_clean %>%
  mutate(Month = factor(Month, levels = month_levels))

```

## Site / edge type

```{r, RQ1 Scarp}

library(tidytext)

site_order <- master_tier5 %>%
  distinct(Site, marsh_edge_type) %>%
  arrange(marsh_edge_type, Site) %>%
  pull(Site)

master_tier5_clean <- master_tier5_clean %>%
  mutate(
    Site = factor(Site, levels = site_order), 
    slope_fitted_elevation_m = as.numeric(slope_fitted_elevation_m)
)


rq1_site = ggplot(master_tier5_clean, aes(x =Site , y = log(Flux),
                                                  fill = marsh_edge_type,
                                                  color = marsh_edge_type)) +
  geom_boxplot(width = 0.4, outlier.shape = NA,
               alpha = 0.3,
               position = position_dodge(0.5)) +
  geom_point(aes(color = marsh_edge_type),
             position = position_jitterdodge(jitter.width = 0.15, dodge.width = 0.5),
             size = 1.5, alpha = 0.3) +
  scale_color_manual(values = marsh_edge_colors) + 
  scale_fill_manual(values = marsh_edge_colors) +
  ylim(0, 6) +
  labs(y = "Log(Flux (g/m^2/day))", x = "Site",
       fill = "Marsh Edge Type", color = "Marsh Edge Type",
       title = str_wrap("Sediment Deposition Rates Across Sites Between Scarped and Ramped Marsh Edge Sites")) +
  theme_bw() +
  theme(legend.position = "bottom")
rq1_site

ggsave("C:\\Users\\savan\\OneDrive - San Francisco State University\\ProjectData\\GitHub\\DepositionSFB\\images\\rq1_site.png", 
       width = 8, 
       height = 5, 
       dpi = 300,
       limitsize = FALSE)

tran_order <- master_tier5_clean %>%
  distinct(Tran, marsh_edge_type) %>%
  arrange(marsh_edge_type, Tran) %>%
  pull(Tran)



rq1_tran = ggplot(master_tier5_clean, aes(x =Site , y = log(Flux),
                                    fill = Tran,
                                    color = Tran)) +
  geom_boxplot(width = 0.4, outlier.shape = NA,
               alpha = 0.3,
               position = position_dodge(0.5)) + facet_wrap(~marsh_edge_type, scales = "free_x") +
  geom_point(aes(color = marsh_edge_type),
             position = position_jitterdodge(jitter.width = 0.15, dodge.width = 0.5),
             size = 1.5, alpha = 0.3) +
 scale_color_manual(values = site_colors) + 
   scale_fill_manual(values = transect_colors) + 
  scale_x_reordered() +
  ylim(0, 6) +
  labs(y = "Log(Flux (g/m^2/day))", x = "Site",
       fill = "Marsh Edge Type", color = "Marsh Edge Type",
       title = str_wrap("Sediment Deposition Rates Across Transects Between Scarped and Ramped Marsh Edge Sites", width = 40)) +
  theme_bw() +
  theme(legend.position = "bottom")
rq1_tran

ggsave("C:\\Users\\savan\\OneDrive - San Francisco State University\\ProjectData\\GitHub\\DepositionSFB\\images\\rq1_tran.png", 
       width = 8, 
       height = 5, 
       dpi = 300,
       limitsize = FALSE)

```

## Distance

```{r, rq1 distance}

rq1_dist = ggplot(master_tier5_clean, aes(x = factor(Dist), y = Flux, color = Tran, fill = Tran)) +
  geom_violin(alpha = 0.3, position = position_dodge(0.8)) +
  geom_jitter(position = position_jitterdodge(jitter.width = 0.15, dodge.width = 0.8),
              size = 1.2, alpha = 0.4) +
  facet_wrap(~Site, scales = "free_y", ncol = 2) +
 scale_color_manual(values = site_colors) + 
  theme_minimal(base_size = 20) +
  labs(x = "Distance", y = expression(Flux~(g/m^2/day)),
       color = "Transect", fill = "Transect") +
  theme(legend.position = "bottom",
        strip.text = element_text(face = "bold", size = 18),
        axis.text = element_text(size = 14),
        axis.title = element_text(size = 18, face = "bold"),
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 16, face = "bold"),
        plot.title = element_text(size = 20, face = "bold"))
rq1_dist

ggsave("C:\\Users\\savan\\OneDrive - San Francisco State University\\ProjectData\\GitHub\\DepositionSFB\\images\\rq1_dist.png",
       plot = rq1_dist,
       width = 13.33,
       height = 7.5,
       dpi = 300,
       limitsize = FALSE)

rq1_dist_noG = ggplot(filter(master_tier5_clean, Site != "GiantMarsh"), 
                      aes(x = factor(Dist), y = Flux, color = Tran, fill = Tran)) +
  geom_violin(alpha = 0.3, position = position_dodge(0.8)) +
  geom_jitter(position = position_jitterdodge(jitter.width = 0.15, dodge.width = 0.8),
              size = 1.2, alpha = 0.4) +
  facet_wrap(~Site, scales = "free_y") +
 scale_color_manual(values = site_colors) + 
  theme_minimal(base_size = 20) +
  labs(x = "Distance", y = expression(Flux~(g/m^2/day)),
       color = "Transect", fill = "Transect") +
  theme(legend.position = "bottom",
        strip.text = element_text(face = "bold", size = 18),
        axis.text = element_text(size = 14),
        axis.title = element_text(size = 18, face = "bold"),
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 16, face = "bold"))
rq1_dist_noG

ggsave("C:\\Users\\savan\\OneDrive - San Francisco State University\\ProjectData\\GitHub\\DepositionSFB\\images\\rq_1\\rq1_dist_noG.png",
       plot = rq1_dist_noG,
       width = 13.33,
       height = 7.5,
       dpi = 300,
       limitsize = FALSE)



rq1_slope = ggplot(master_tier5_clean, 
                      aes(x = factor(slope_fitted_elevation_m), y = Flux, color = Tran, fill = Tran)) +
  geom_violin(alpha = 0.3, position = position_dodge(0.8)) +
  geom_jitter(position = position_jitterdodge(jitter.width = 0.15, dodge.width = 0.8),
              size = 1.2, alpha = 0.4) +
  facet_wrap(~Site, scales = "free_y") +
 scale_color_manual(values = site_colors) + 
  theme_minimal(base_size = 20) +
  labs(x = "Slope Per Transect (m)", y = expression(Flux~(g/m^2/day)),
       color = "Transect", fill = "Transect") +
  theme(legend.position = "bottom",
        strip.text = element_text(face = "bold", size = 18),
        axis.text = element_text(size = 14),
        axis.title = element_text(size = 18, face = "bold"),
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 16, face = "bold"))
rq1_slope


ggsave("C:\\Users\\savan\\OneDrive - San Francisco State University\\ProjectData\\GitHub\\DepositionSFB\\images\\rq_1\\rq1_slope.png",
       plot = rq1_slope,
       width = 13.33,
       height = 7.5,
       dpi = 300,
       limitsize = FALSE)
```

```{r}

master_tier5_clean <- master_tier5_clean %>%
  mutate(Site_Tran = paste(Site, Tran, sep = " - "))

rq1_ramped = ggplot(filter(master_tier5_clean, marsh_edge_type == "Ramped"), 
                    aes(x = factor(Dist), y = Flux, color = Site_Tran, fill = Site_Tran)) +
  geom_violin(alpha = 0.3, position = position_dodge(0.8)) +
  geom_jitter(position = position_jitterdodge(jitter.width = 0.15, dodge.width = 1.2),
              size = 0.8, alpha = 0.3) +
  scale_fill_manual(values = site_colors) + 
  theme_minimal(base_size = 13) +
  labs(x = "Distance", y = expression(Flux~(g/m^2)),
       color = "Site - Transect", fill = "Site - Transect",
       title = "Sediment Deposition Rates Across Ramped Sites") +
  theme(legend.position = "bottom")
rq1_ramped

rq1_scarped = ggplot(filter(master_tier5_clean, marsh_edge_type == "Scarped"), 
                     aes(x = factor(Dist), y = Flux, color = Site_Tran, fill = Site_Tran)) +
  geom_violin(alpha = 0.3, position = position_dodge(0.8)) +
  geom_jitter(position = position_jitterdodge(jitter.width = 0.15, dodge.width = 1.2),
              size = 0.8, alpha = 0.3) +
  scale_fill_manual(values = site_colors)
  theme_minimal(base_size = 13) +
  labs(x = "Distance", y = expression(Flux~(g/m^2)),
       color = "Site - Transect", fill = "Site - Transect",
       title = "Sediment Deposition Rates Across Scarped Sites") +
  theme(legend.position = "bottom")
rq1_scarped

```

## Elevation (z*)

```{r}

rq1_z = ggplot(master_tier5_clean, aes(x = z_star, y = Flux, color = Tran)) +
  geom_point(alpha = 0.4, size = 1.5) +
  geom_rug(sides = "b", alpha = 0.3, length = unit(0.03, "npc")) +
  facet_wrap(~Site, scales = "free") +
  scale_color_manual(values = c("T1" = "#D85A30", "T2" = "#378ADD")) +
  theme_minimal(base_size = 16) +
  labs(x = "Relative Elevation (Z*)", y = expression(Flux~(g/m^2/day)),
       color = "Transect") +
  theme(strip.text = element_text(face = "bold", size = 16),
        axis.title = element_text(face = "bold", size = 15),
        axis.text = element_text(size = 12))
rq1_z

ggsave("C:\\Users\\savan\\OneDrive - San Francisco State University\\ProjectData\\GitHub\\DepositionSFB\\images\\rq_1\\rq1_z.png",
       plot = rq1_z,
       width = 13.33,
       height = 7.5,
       dpi = 300,
       limitsize = FALSE)


```

```{r}

master_tier5_clean <- master_tier5 |> 
  filter(Flux > 0)  # removes negatives and zeros

sum(master_tier5_clean$Flux <= 0, na.rm = TRUE)  # should return 0
summary(master_tier5_clean$Flux)


library(lme4)
model <- lmer(log(Flux) ~ z_star * marsh_edge_type + (1|Site) + (1|Study.Phase), 
              data = master_tier5_clean)
summary(model)

library(lmerTest)
model_full <- lmer(log(Flux) ~ z_star * marsh_edge_type + 
                     (1 | Site) + (1 | Study.Phase),  
                   data = master_tier5_clean,
                   REML = FALSE)
summary(model_full)

library(MuMIn)
r.squaredGLMM(model_full)

library(emmeans)
emtrends(model_full, ~ marsh_edge_type, var = "z_star")

library(ggeffects)
pred <- ggpredict(model_full, terms = c("z_star [all]", "marsh_edge_type"))

ggplot(pred, aes(x = x, y = predicted, color = group, fill = group)) +
  geom_line(linewidth = 1.2) +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = 0.2, color = NA) +
  geom_point(data = master_tier5_clean, 
             aes(x = z_star, y = log(Flux), color = marsh_edge_type),
             alpha = 0.3, size = 1.5, inherit.aes = FALSE) +
  scale_color_manual(values = marsh_edge_colors) + 
  labs(x = "z*", 
       y = "log(Sediment Flux g/m²)",
       color = "Edge Type", 
       fill  = "Edge Type",
       title = "Sediment Deposition by Marsh Edge Morphology") +
  theme_bw() +
  theme(legend.position = "right")
```

## Distance models

```{r, distance model prep}

avgdist <- aggregate(Flux ~ Dist + Site + Tran, data = master_tier5_clean, FUN = mean) %>%
  filter(Dist != 48) %>%
  mutate(Dist = factor(Dist, levels = c(0.5, 2, 6, 12, 18, 24)))

shapiro.test(avgdist$Flux)
shapiro.test(log(avgdist$Flux))

qqnorm(avgdist$Flux)
qqline(avgdist$Flux)

```

```{r, distance models}
distmodel <- glmer(Flux ~ Dist + (1|Site) + (1|Tran), data = avgdist)
summary(distmodel)

logdistmodel <- lmer(log(Flux) ~ Dist + (1|Site) + (1|Tran), data = avgdist)
summary(logdistmodel)

plot(logdistmodel)        # residuals vs fitted
qqnorm(resid(logdistmodel))
qqline(resid(logdistmodel))

# Outlier check
outliers <- which(abs(scale(resid(logdistmodel))) > 2.5)
distmodel_no_outliers <- lmer(log(Flux) ~ Dist + (1|Site) + (1|Tran),
                              data = avgdist[-outliers, ])
summary(logdistmodel)
summary(distmodel_no_outliers)

distmodelcont <- lmer(log(Flux) ~ Dist + (1|Site) + (1|Tran), data = avgdist)
summary(distmodelcont)
```

```{r, distance x site model and plots}
  distsitemodel <- lmer(log(Flux) ~ Dist + Site + Dist*Site + (1|Tran), data = avgdist)
summary(distsitemodel)

avgdist$predicted <- predict(distsitemodel)
preds <- ggpredict(distsitemodel, terms = c("Dist [all]", "Site"), back.transform = FALSE)

ggplot() +
  geom_point(data = avgdist,
             aes(x = Dist, y = log(Flux), colour = Site, shape = Site),
             size = 3, alpha = 0.5) +
  geom_line(data = preds,
            aes(x = x, y = predicted, colour = group, group = group),
            linewidth = 1) +
  scale_color_manual(values = site_colors) + 
  geom_ribbon(data = preds,
              aes(x = x, ymin = conf.low, ymax = conf.high, fill = group, group = group),
              alpha = 0.2) +
  labs(x = "Distance (m)", y = "Log of Average Flux (g/cm^2/day)",
       colour = "Site", fill = "Site", shape = "Site") +
  theme_classic(base_size = 16)

pred_grid <- expand.grid(
  Dist = factor(levels(avgdist$Dist), levels = levels(avgdist$Dist)),
  Site = unique(avgdist$Site),
  Tran = NA
)

preds_manual <- predict(distsitemodel, newdata = pred_grid,
                        re.form = ~0, se.fit = TRUE)

pred_grid$predicted <- preds_manual$fit
pred_grid$lower <- preds_manual$fit - 1.96 * preds_manual$se.fit
pred_grid$upper <- preds_manual$fit + 1.96 * preds_manual$se.fit

ggplot() +
  geom_point(data = avgdist,
             aes(x = Dist, y = log(Flux), colour = Site, shape = Site),
             size = 3, alpha = 0.5) +
  geom_line(data = pred_grid,
            aes(x = Dist, y = predicted, colour = Site, group = Site),
            linewidth = 1) +
  geom_ribbon(data = pred_grid,
              aes(x = Dist, ymin = lower, ymax = upper, fill = Site, group = Site),
              alpha = 0.2) +
  scale_color_manual(values = site_colors) + 
  labs(x = "Distance (m)", y = "Log of Average Flux (g/cm^2/day)",
       colour = "Site", fill = "Site", shape = "Site") +
  theme_classic(base_size = 18) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 15))

```

## Transect x Site

```{r, transect x site model}
 
library(ggforce)  # for geom_sina() in the reference-additions plots

 transite <- lmer(log(Flux) ~ Tran + Site + Tran*Site + (1|Dist), data = avgdist)
  summary(transite)
  
tran_site = ggplot(avgdist, aes(x = as.factor(Tran), y = log(Flux), fill = Site, colour = Site)) +
    geom_boxplot(alpha = 0.4, outlier.shape = NA) +
    geom_sina(alpha = 0.6, size = 2) +
    labs(x = "Transect", y = "Log of Average Flux (g/cm^2/day)",
         fill = "Site", colour = "Site") +
    scale_color_manual(values = site_colors) + 
    scale_fill_manual(values = site_colors) +
    theme_classic(base_size = 18) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 18))
  
ggsave("C:\\Users\\savan\\OneDrive - San Francisco State University\\ProjectData\\GitHub\\DepositionSFB\\images\\rq_1\\tran_site.png", 
       plot = tran_site, 
       width = 8, 
       height = 5, 
       dpi = 300,
       limitsize = FALSE)
 
```

```{r, transect x site model with replicate}
# transite1's formula includes (1|Study.Phase) purely as a temporal
# control, the same way (1|Dist) controls for distance above -- the
# model's actual question is still the Tran x Site interaction, so it
# stays here. Its Study.Phase sina plot and Dist x Study.Phase facet plot
# moved to RQ1-temporal.qmd, since those show patterns across time, not
# across site/space.

master_tier5_clean <- master_tier5_clean[master_tier5_clean$Flux > 0 &
                                     !is.na(master_tier5_clean$Flux) &
                                     is.finite(log(master_tier5_clean$Flux)), ]

sum(is.na(master_tier5_clean$Flux))
sum(master_tier5_clean$Flux <= 0)
nrow(master_tier5_clean)

master_tier5_clean$Tran <- as.factor(master_tier5_clean$Tran)
master_tier5_clean$Site <- as.factor(master_tier5_clean$Site)
master_tier5_clean$Replicate <- as.factor(master_tier5_clean$Replicate)
master_tier5_clean$Study.Phase <- factor(master_tier5_clean$Study.Phase,  levels = paste0("M", 1:12))

transite1 <- lmer(log(Flux) ~ Tran + Site + Tran*Site +
                    (1|Dist) + (1|Replicate) + (1|Study.Phase),
                  data = master_tier5_clean)
summary(transite1)

ggplot(master_tier5_clean, aes(x = as.factor(Tran), y = log(Flux), fill = Site, colour = Site)) +
  geom_boxplot(alpha = 0.4, outlier.shape = NA) +
  geom_sina(alpha = 0.6, size = 2) +
  facet_wrap(~Site, scales = "free_x") +
  labs(x = "Transect", y = "Log of Average Flux (g/cm^2/day)",
       fill = "Site", colour = "Site") +
  scale_color_manual(values = marsh_edge_colors) + 
  theme_classic(base_size = 18) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 18),
        axis.text.y = element_text(hjust = 1, size = 12))
```

## Marsh edge type and orientation

```{r, marsh edge type and orientation model prep}

  avgtotal <- aggregate(Flux ~ Site + Dist + Replicate + Study.Phase +
                          marsh_orientation + marsh_edge_type,
                        data = master_tier5_clean, FUN = mean)
  str(avgtotal)
  
  shapiro.test(avgtotal$Flux)
  shapiro.test(log(avgtotal$Flux))
  
  qqnorm(avgtotal$Flux)
  qqline(avgtotal$Flux)
  
  shapiro.test(resid(distsitemodel))
  qqnorm(resid(distsitemodel))
  qqline(resid(distsitemodel))


```

```{r, marsh edge type and orientation models}
marsh_edge_model_edge <- lmer(Flux ~ marsh_edge_type + (1|Dist), data = master_tier5_clean)
summary(marsh_edge_model_edge)

marsh_edge_model_sitetran <- lmer(Flux ~ marsh_edge_type + (1|Site/Tran), data = master_tier5_clean)
summary(marsh_edge_model_sitetran)


marsh_edge_model_orient <- lmer(Flux ~ marsh_orientation + (1|Dist), data = master_tier5_clean)
summary(marsh_edge_model_orient)

marsh_edge_model_orient <- lmer(Flux ~ marsh_orientation + (1|Site/Tran), data = master_tier5_clean)
summary(marsh_edge_model_orient)

library(emmeans)
emmeans(marsh_edge_model_edge, pairwise ~ marsh_edge_type, adjust = "tukey")

```

```{r}

marsh_group_flux <- master_tier5_clean %>% 
  mutate(Marsh_Group = case_when(
    Site %in% c("SanPablo", "GiantMarsh") ~ "OpenBay", 
    Site %in% c("CorteMadera", "Buck'sLanding") ~ "Protected", 
    TRUE ~ NA_character_
  ))

marsh_group_model <- lmer(Flux ~ Marsh_Group + (1 | Site) + (1 | Tran), data = marsh_group_flux)
summary(marsh_group_model)
anova(marsh_group_model)
```


```{r, slope as covariate (RQ3 question)}

deposition_model_slope <- lmer(Flux ~ z_star + local_slope + (1 | Site), data = master_tier5_clean)
summary(deposition_model_slope)

deposition_model_base <- lmer(Flux ~ z_star + (1 | Site), data = master_tier5_clean)
anova(deposition_model_base, deposition_model_slope)
```

```{r, testing model without 48-maybe should be data prep let's see}


#model_with_48 <- lmer(Flux ~ Dist + (1 | Site), data = master_tier5)
#model_without_48 <- lmer(Flux ~ Dist + (1 | Site), data = filter(master_tier5, Dist != 48))

#summary(model_with_48)
#summary(model_without_48)

#master_tier5_clean %>%
 # filter(Dist == 48) %>%
  #summarise(n = n(), mean_flux = mean(Flux, na.rm = TRUE), sd_flux = sd(Flux, na.rm = TRUE))

#master_tier5_clean %>%
  #summarise(n = n(), mean_flux = mean(Flux, na.rm = TRUE), sd_flux = sd(Flux, na.rm = TRUE))
```

```{r}
library(moments)
library(car)

master_tier5_clean %>%
  group_by(Site) %>%
  summarise(
    skew = skewness(Flux, na.rm = TRUE),
    sd = sd(Flux, na.rm = TRUE),
    iqr = IQR(Flux, na.rm = TRUE)
  )

leveneTest(Flux ~ Site, data = master_tier5_clean)
```



```{r, marsh edge type and orientation plots}
ggplot(avgtotal, aes(x = marsh_edge_type, y = log(Flux), fill = marsh_orientation)) +
  geom_boxplot(alpha = 0.4, outlier.shape = NA) +
  geom_sina(alpha = 0.6, size = 2, aes(colour = marsh_orientation)) +
  labs(x = "Marsh Edge Type", y = "Log of Average Flux (Log of Average Flux (g/cm^2/day))",
       fill = "Marsh Orientation", colour = "Marsh Orientation") +
  theme_classic(base_size = 18) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 18))

ggplot(master_tier5_clean, aes(x = marsh_edge_type, y = log(Flux), fill = marsh_orientation)) +
  geom_violin(alpha = 0.6) +
  geom_boxplot(width = 0.2, position = position_dodge(0.9)) +
  scale_fill_manual(values = c("East.facing" = "#E07070",
                               "South.facing" = "#70B870",
                               "West.facing" = "#7090D0")) +
  theme_bw()

basic_rq1 = ggplot(avgtotal, aes(x = marsh_edge_type, y = Flux, fill = marsh_edge_type)) +
  geom_boxplot(alpha = 0.5, outlier.shape = NA) +
  geom_jitter(alpha = 0.4, width = 0.2, size = 0.8) +
  scale_y_log10() +
  labs(title = str_wrap("Sediment Flux by Marsh Edge Type", width = 40),
       y = "Average Flux (g/m^2/day)", x = "Marsh Edge Type") +
  theme_bw() +
  scale_fill_manual(values = marsh_edge_colors) + 
  theme(legend.position = "none",
        axis.text.x = element_text(size = 13),
        axis.title = element_text(size = 13),
        plot.title = element_text(hjust = 0.5))
basic_rq1

ggsave("C:\\Users\\savan\\OneDrive - San Francisco State University\\ProjectData\\GitHub\\DepositionSFB\\images\\rq_1\\basic_rq1.png", 
       plot = basic_rq1, 
       width = 8, 
       height = 5, 
       dpi = 300,
       limitsize = FALSE)

ggplot(avgtotal, aes(x = marsh_orientation, y = Flux, fill = marsh_orientation)) +
  geom_boxplot(alpha = 0.5, outlier.shape = NA) +
  geom_jitter(alpha = 0.4, width = 0.2, size = 0.8) +
  scale_y_log10() +
  labs(title = str_wrap("Sediment Flux by Marsh Orientation", width = 40),
       y = "Log of Average Flux (g/cm^2/day)", x = "Marsh Orientation") +
  theme_bw() +
  scale_color_manual(values = marsh_edge_colors) + 
  theme(legend.position = "none",
        axis.text.x = element_text(size = 13),
        axis.title = element_text(size = 13),
        plot.title = element_text(hjust = 0.5))
```

```{r}
library(ggplot2)
library(dplyr)

# Raw data only, WITH 48m point — no trend line
p_with_48 <- ggplot(master_tier5, aes(x = Dist, y = Flux)) +
  geom_point(alpha = 0.3, color = "steelblue") +
  labs(title = "Flux vs. Distance — With 48m Point", x = "Distance (m)", y = "Flux") +
  theme_bw()

#Raw data only, WITHOUT 48m point — no trend line
p_without_48 <- ggplot(filter(master_tier5_clean, Dist != 48), aes(x = Dist, y = Flux)) +
  geom_point(alpha = 0.3, color = "darkred") +
  labs(title = "Flux vs. Distance — Without 48m Point", x = "Distance (m)", y = "Flux") +
  theme_bw()

p_with_48
p_without_48
```


```{r}

library(ggeffects)
library(ggplot2)

# effect of z_star, holding local_slope constant
plot_zstar <- ggpredict(deposition_model_slope, terms = "z_star") %>%
  plot() +
  labs(title = "Predicted Flux by Z-star", x = "Z-star", y = "Predicted Flux") +
  theme_bw()

# effect of local_slope, holding z_star constant
plot_slope <- ggpredict(deposition_model_slope, terms = "local_slope") %>%
  plot() +
  labs(title = "Predicted Flux by Local Slope", x = "Local Slope", y = "Predicted Flux") +
  theme_bw()

plot_zstar
plot_slope


```


```{r}

library(emmeans)
library(ggplot2)

marsh_group_model <- lmer(Flux ~ Marsh_Group + (1 | Site) + (1 | Tran), data = marsh_group_flux)

summary(marsh_group_model)

emm_marsh_group <- emmeans(marsh_group_model, ~ Marsh_Group)
emm_marsh_group_df <- as.data.frame(emm_marsh_group)

ggplot(emm_marsh_group_df, aes(x = Marsh_Group, y = emmean)) +
  geom_col(fill = "steelblue", width = 0.5) +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = 0.15) +
  labs(
    title = "Estimated Marginal Means of Flux by Geomorphic Grouping",
    y = "Estimated Flux", x = "Marsh Group"
  ) +
  theme_bw()
```


```{r, variance across scarped vs. ramped sites}

master_tier5_clean %>%
  group_by(Site, marsh_edge_type, Study.Phase) %>%
  summarise(monthly_mean = mean(Flux, na.rm = TRUE), .groups = "drop") %>%
  group_by(Site, marsh_edge_type) %>%
  summarise(temporal_var = var(monthly_mean, na.rm = TRUE), .groups = "drop")
```
```{r}
master_tier5_clean %>%
  group_by(Site, marsh_edge_type, Dist) %>%
  summarise(monthly_mean = mean(Flux, na.rm = TRUE), .groups = "drop") %>%
  group_by(Site, marsh_edge_type) %>%
  summarise(spatial_var = var(monthly_mean, na.rm = TRUE), .groups = "drop")
```

```{r}
avgdist_protected <- avgdist %>%
  filter(!Site %in% c("SanPablo", "GiantMarsh"))
```


```{r}
BCtransite <- lmer(log(Flux) ~ Tran + Site + Tran*Site + (1|Dist), data = avgdist_protected)
summary(BCtransite)

BCtransite = ggplot(avgdist_protected, aes(x = as.factor(Tran), y = log(Flux), fill = Site, colour = Site)) +
  geom_boxplot(alpha = 0.4, outlier.shape = NA) +
  geom_sina(alpha = 0.6, size = 2) +
  labs(x = "Transect", y = "Log of Average Flux (g/cm^2/day)",
       fill = "Site", colour = "Site") +
  scale_color_manual(values = site_colors) +
  scale_fill_manual(values = site_colors) + 
  theme_classic(base_size = 18) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 18))

ggsave("C:\\Users\\savan\\OneDrive - San Francisco State University\\ProjectData\\GitHub\\DepositionSFB\\images\\rq_1\\BCtransite.png", 
       width = 8, 
       height = 5, 
       dpi = 300,
       limitsize = FALSE)
```


```{r}

p_flux_zstar <- ggplot(master_tier5_clean, aes(x = z_star, y = Flux, color = Site)) +
  geom_point(size = 2, alpha = 0.7) +
  scale_color_manual(values = site_colors) +
   scale_y_log10() +
  labs(
    title = str_wrap("Daily Sediment Flux vs. Elevation (z*) Across 2 Ramped and 2 Scarped Marshes, 2025-2026 ", width = 40),
    x = "z*",
    y = expression(Flux~(g/m^2/day)),
    color = "Site"
  ) +
  theme_minimal() +
  theme(legend.position = "bottom")
p_flux_zstar


ggsave("C:\\Users\\savan\\OneDrive - San Francisco State University\\ProjectData\\GitHub\\DepositionSFB\\images\\rq_1\\p_flux_zstar.png", 
       plot = p_flux_zstar,
       width = 8, 
       height = 5, 
       dpi = 300,
       limitsize = FALSE)
```




```{r}

site_stats <- make_flux_table(
  master_thesis, 
  group_vars = "Site", 
  title = "Descriptive Statistics of Sediment Flux by Site",
  subtitle = "Flux measured in g/m²/day"
)
```

```{r}
ft <- site_stats$data %>%
  flextable() %>%
  set_caption("Descriptive Statistics of Sediment Flux by Site") %>%
  colformat_double(digits = 3) %>%
  autofit()

save_as_image(ft, path = "C:\\Users\\savan\\OneDrive - San Francisco State University\\ProjectData\\GitHub\\DepositionSFB\\images\\rq_1\\site_flux_stats.png")
```

```

